[build]
  base = "client"
  command = "node -v && npm -v && ls -la && npm ci --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

